### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by simsdj** [ninjaprawn/async_awake-fun#1]

**Comment by hacx** [comment]
says libproc.h not found

**Comment by simsdj** [comment]
mine says a whole bunch of stuff

**Comment by hacx** [comment]
Make sure you compile for device and not simulator

**Comment by simsdj** [comment]
I've tried on a 6s+ and a X and they both say the same things

**Comment by Rybo713** [comment]
I just deleted that line `#include <libproc.h>` and it worked afterwards.

**Comment by simsdj** [comment]
You're a genius
