### ISSUE TITLE
Kernel panic on iPad Air 2

### ISSUE THREAD

**Issue by AlexeyGorbushin** [ninjaprawn/async_awake-fun#11]
The app causes the kernel panic on iPad Air 2.
The crash happens in:
```
void let_the_fun_begin(mach_port_t tfp0, mach_port_t user_client) {
...
    uint64_t bol = ZM_FIX_ADDR(kexecute(0xFFFFFFF0074A68C8+slide, 1, 0, 0, 0, 0, 0, 0));
...
}
```

```
uint64_t kexecute(mach_port_t user_client, uint64_t fake_client, uint64_t addr, uint64_t x0, uint64_t x1, uint64_t x2, uint64_t x3, uint64_t x4, uint64_t x5, uint64_t x6) {
...
    uint64_t returnval = iokit_user_client_trap(user_client, 0, (uint64_t)(x1), (uint64_t)(x2), (uint64_t)(x3), (uint64_t)(x4), (uint64_t)(x5), (uint64_t)(x6)); // <---  crash is here
}
```
What is the constant address 0xFFFFFFF0074A68C8?

**Comment by ghost** [comment]
I am also getting a panic on my iPhone SE :( The panic log shows that it is detecting a kernel stack memory corruption

**Comment by ghost** [comment]
Huh weird, if i set a breakpoint at `void let_the_fun_begin`, then there are no errors and i can use lldb with no problems...

**Comment by ninjaprawn** [comment]
I left some hard coded offsets for slides for testing around. Feel free to comment them out (ill be sure to do so in my next commit.
