### ISSUE TITLE
Kernel panic on iPhone SE

### ISSUE THREAD

**Issue by ghost** [ninjaprawn/async_awake-fun#14]
My phone would normally generate a kernel panic stating that there was a kernel stack memory corruption detected. I commented out that one line and everything worked fine (despite it not being able to read/write to kernel memory). Can anyone help?

**Comment by ghost** [comment]
`init_kernel_utils(tfp0, user_client);` is what causes the panic

**Comment by ghost** [comment]
In fun_utils.c (I think, I don’t have my Mac with me rn)

**Comment by ninjaprawn** [comment]
If you have run the project numerous times beforehand, then its just a memory issue which can be resolved via a `term_kern()` call or something like that at the end of fun.c

If this is a first time, that is interesting. init_kernel_utils does nothing apart from setting a variable. Could you try again?

**Comment by ghost** [comment]
I think I ran benjibobs version of it before. I’ll try adding term_kern() to the end of fun.c

**Comment by ghost** [comment]
@ninjaprawn didn't fix it. The end of my fun.c looks like this:
`//	char *nmz = strdup("/dev/disk0s1s1");
//	rv = mount("hfs", "/", MNT_UPDATE, (void *)&nmz);
//	printf("[fun] remounting: %d\n", rv);
	
	kwrite64(IOSurfaceRootUserClient_port + koffset(KSTRUCT_OFFSET_IPC_PORT_IP_KOBJECT), IOSurfaceRootUserClient_addr);
	kwrite64(kread64(kern_ucred+0x78)+0x8, 0);
    term_kernel();
}`

and the end of the output is this:
`got replaced with replacer port 51
found kernel vm_map: 0xfffffff104451c40
second time got replaced with replacer port 0
will try to read from second port (fake kernel)
kernel read via fake kernel task port worked?
0x0000000000420000
0x0000000000000000
0xfffffff10447a460
0xfffffff10447a410
about to build safer tfp0
message buffer: fffffff10bd19000
fake_kernel_task_kaddr: fffffff10bd19000
read fake_task_refs: d00d
about to test new tfp0
kernel read via second tfp0 port worked?
0x0000000000420000
0x0000000000000000
0xfffffff10447a460
0xfffffff10447a410
built safer tfp0
about to clear up
cleared up
tfp0: 1888e0b
[fun] slide: 0x0000000001a00000
[fun] Created fake_vtable at fffffff002b04000
[fun] Copied some of the vtable over
[fun] Created fake_client at fffffff002b08000
[fun] Copied the user client over
[fun] Wrote the `add x0, x0, #0x40; ret;` gadget over getExternalTrapForIndex
`

**Comment by ghost** [comment]
I am pretty sure it is that line as when i comment it out everything runs, somewhat, smoothly

**Comment by ghost** [comment]
If it helps here is my panic log:
[KernelPanicLog.txt](https://github.com/ninjaprawn/async_awake-fun/files/1580761/KernelPanicLog.txt)
And the xcode output:
[AsyncWakeFunOutput.txt](https://github.com/ninjaprawn/async_awake-fun/files/1580766/AsyncWakeFunOutput.txt)

**Comment by ghost** [comment]
Is it maybe that the gadget is not being written properly? The kernel is detecting memory corruption, or is the corruption just because it has detected  code being written where it shouldn’t be?

**Comment by ninjaprawn** [comment]
ah ok i know the problem i think im just about to push some changes which comments out a whole bunch of testing i was doing plus something else

**Comment by ghost** [comment]
@ninjaprawn  Ok thanks!

**Comment by ninjaprawn** [comment]
sorry for the delay i was being silly while trying to write what i think is an amfid patch the thing should run properly now - ive commented out all the code that has hardcoded offsets
