### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by Champ-Goblem** [ninjaprawn/async_awake-fun#19]
Something in fun.c causing kernel panic on iPhone 6, IOS version 11.0.3. Provided the crash log too for extra info.
![image](https://user-images.githubusercontent.com/19267423/34281304-b878dcd0-e6b5-11e7-99e5-a6b0bdb6d81c.png)
[Unknown (null).txt](https://github.com/ninjaprawn/async_awake-fun/files/1581177/Unknown.null.txt)

**Comment by ninjaprawn** [comment]
try it out now i was using hardcoded offsets for testing purposes but it should work now

**Comment by Champ-Goblem** [comment]
Seems perfect cheers for that, doesn't crash the device and kills the resident process.
