### ISSUE TITLE
[QUESTION]What happened to lldb debugging?

### ISSUE THREAD

**Issue by ghost** [ninjaprawn/async_awake-fun#20]
Before in the xcode console an lldb prompt would appear. Doesnt anymore?

**Comment by stek29** [comment]
Probably because there are no breakpoints

**Comment by ghost** [comment]
How do breakpoints affect whether lldb prompts appear or not?

**Comment by ninjaprawn** [comment]
If you mean for the app itself, the app is killed after everything has finished running

**Comment by ghost** [comment]
even when i get rid of the kill line, the lldb prompt still doesnt show up

**Comment by ninjaprawn** [comment]
You need to set a breakpoint to get the prompt to show up (or something like debug menu, stop/suspend or something)

**Comment by ghost** [comment]
Oh ok
