### ISSUE TITLE
Now kernel panics everytime it's ran

### ISSUE THREAD

**Issue by JosephShenton** [ninjaprawn/async_awake-fun#22]
Hi, async_wake-fun current commit was working fine until about half an hour ago where i started getting kernel panics everytime i ran async_wake-fun, i didn't change any code from the working version at all.

**Comment by stek29** [comment]
With what message does it panic?
What if you remove inject_amfid stuff?

**Comment by JosephShenton** [comment]
i'm in the middle of updating xcode it's almost done so I'll send the message and trying removing inject_amfid once it's done
