### ISSUE TITLE
Springboard: (os/kern) failure

### ISSUE THREAD

**Issue by ghost** [ninjaprawn/async_awake-fun#6]
![screen shot 2017-12-17 at 18 36 28](https://user-images.githubusercontent.com/11149719/34082146-3afebf90-e359-11e7-8652-3fe2a182f126.png)

getting this error on iPhone SE (11.1.1) and 5s (11.1.2)

**Comment by CLATechTeam** [comment]
Same issue for me... solution?

**Comment by ghost** [comment]
Delete this line >
Line 37
 kill(getpid(), SIGKILL);

**Comment by CLATechTeam** [comment]
I will try what you told me and let you know if it works :)
