### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by riccardoruspoli** [ninjaprawn/async_awake-fun#8]
"_file_exist", referenced from:

_let_the_fun_begin in fun.o

"_get_code_directory", referenced from:

_let_the_fun_begin in fun.o

"_get_sha256", referenced from:

_let_the_fun_begin in fun.o

"_kalloc", referenced from:

_let_the_fun_begin in fun.o

(maybe you meant: _early_kalloc, _message_size_for_kalloc_size , _send_kalloc_message )

"_kwrite", referenced from:

_let_the_fun_begin in fun.o

"_kwrite32", referenced from:

_let_the_fun_begin in fun.o

"_init_kernel_utils", referenced from:

_let_the_fun_begin in fun.o

"_kread32", referenced from:

_let_the_fun_begin in fun.o

"_kread", referenced from:

_let_the_fun_begin in fun.o

_init_kernel in patchfinder64.o

"_kread64", referenced from:

_kexecute in fun.o

_let_the_fun_begin in fun.o

"_cp", referenced from:

_let_the_fun_begin in fun.o

"_kwrite64", referenced from:

_kexecute in fun.o

_let_the_fun_begin in fun.o

Symbol(s) not found for architecture arm64

**Comment by MrARM** [comment]
I second this, I have cloned from git and built it in xcode 9

**Comment by hieplpvip** [comment]
Add "fun_utils.h" and "fun_utils.m" to project and you should be able to run it

**Comment by ninjaprawn** [comment]
Forgot to commit the xcode project file before so the files were not recognised by xcode :3 Should work now

**Comment by riccardoruspoli** [comment]
Thank you.
