### ISSUE TITLE
qwertyoruiop's kpp bypass

### ISSUE THREAD

**Issue by hieplpvip** [ninjaprawn/async_awake-fun#9]
Luca said that his kpp bypass from yalu102 still work in ios 11.1.2 with few changes. Have you try it?

**Comment by nullpixel** [comment]
We don’t need it; this is a kppless jailbreak.

**Comment by stek29** [comment]
@hieplpvip luca's kpp bypass is extremely complicated, and isn't required on this JB 
Would be cool to have it updated for iOS 11, but imo it's out of scope of this JB

**Comment by ninjaprawn** [comment]
https://github.com/ninjaprawn/async_awake-fun/blob/master/async_wake_ios/AppDelegate.m#L32:

```objc
NSLog(@" ♫ KPP never bothered me anyway... ♫ ");
```

(in all seriousness, i think it would be good to get some form of a kppless "jb" going so that we don't have to worry about it in the future)
